### PR TITLE
Feature/refactoring-for-webgl2

### PR DESCRIPTION
**Pull request by VirgiliuC**
We have refactored dicom.ts for working with WebGL2, introducing significant changes into the code, while keeping as much as possible the structure and the interfaces. Webgl2 is available on many mobile devices too, and is crucial for modern Dicom images rendering and MPR. We envisage using it as such in our clinical environment. In a nutshell:

- migrated to Texture3D
- added Sagittal and Coronal views, using 3D texture
- updated all the GLSL programs for webgl2 and 3D textures
- fixed bugs in Series and started using it for ordering and FrameInfo generation
- the Renderer accepts now several Series to be rendered as transparent (alpha-blending) overlays; useful on image registration, radiation dose over CT scans, etc.
- each image series can be modulated with an external colour, for image registration, blending, etc.
- the Renderer accepts an external (transparent) overlay, where one can set annotations, image segmentation (contours), etc.
- the Renderer accepts an external solid (opaque) overlay, where one can render various tools, like rulers, protractor, graticules, etc.
- separated the webgl rendering code away from other code
- updated the examples to work within the new context (some 2D images now may exceed the maximum allowed 3D size!)
- various other code changes, fixes, refactoring

### CODE REVIEW

**Comment by nickhingston** [comment]
Wow thanks! Only just noticed this PR - will be reviewing it over the next few days.

**Comment by VirgiliuC** [comment]
Maybe should close this one and re-issue it, because since then we further developed the code in this regard, fixed more bugs and added some required functionality/behaviour. Happy to that, if you would like.

**Comment by nickhingston** [comment]
OK, aborted review - some comments on what I'd looked at.  big one being ignoring eslint on ./src!

TBH, we'd be keeping this on a feature branch for a while anyway - we need to support iOS 13 for now - which doesn't support WebGL2.

Our main use case for this library at the moment is single image radiographs, and any loss of resolution in 2d rendering capability would be unacceptable for us, maybe there is a way of combining both solutions.  Interested to know the 3d limitation?

The way we use this library is also to BLT the output on to a separate, canvas - which we render tools, overlays, perform zoom on etc.  Like to know some more about your use case, do you need to draw tools etc between the z orders of your images?  do you need to view the image(s) in different planes? 

Certainly interested in the series bugfixes.

**Comment by VirgiliuC** [comment]
To answer your questions:
 - yes, I'm planning for the single 2D images to use 2D textures, which will allow larger image sizes, probably up to > 16k pixel width/height on desktops, and use 3D textures only on multi-frame or volume series, or CT/MR etc.
 - also, yes, since then we've been developing a proper viewer built on top of (our version of) dicom.ts. This allows simultaneous multiple views in various layouts and combinations, each view has zooming and panning and has a collection of tools, like: info overlays, image sampler, rulers, and cross-hairs for defining slicing planes . These tools work on all views: axial, sagittal, coronal.
 - also, since placing this PR, we have developed on top of dicom.ts the dicomrt.ts, which adds the rendering of image segmentations (organ outlines) of top of the images, but using the renderer from dicom.ts (and twgl). Also, it allows editing these contours using pens or circular brushes.
 - the things you commented about were, tbh, quick fixes to make the code run properly on our Windows environment, and forgot to redo for a cross-platform setup.
 It would be a pity though for parallel 'dicom.ts' developments in the roughly same direction, but indeed we do not use iOS, but we use routinely CT/MR, multi-frames and volume images (in oncology). Hence this development.

**Comment by nickhingston** [comment]
WebGL2 comes in at iOS15 - so within the next 1-2 years will be happy to drop 1.

I'll close this PR then, and feel free to open another.  Certainly interested in future collaboration here.

**Pull request closed without merging**
